config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'dashboard', to: 'pages#dashboard'
  get 'profile', action: :show, controller: 'users'

  get 'signup', to: 'pages#signup'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users do
    resources :dogs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dogs
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 4, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: {case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { in: 6..20 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  helper ApplicationHelper

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @dog = Dog.new
  end

  def edit
    @user = User.find(params[:user_id])
    @dog = @user.dogs.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
    @dog = @user.dogs.create(dog_params)

    redirect_to user_path(@user)
  end

  def update
    @user = User.find(params[:user_id])
    @dog = @user.dogs.find(params[:id])

    if @dog.update(dog_params)
      redirect_to @dog
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @dog = @user.dogs.find(params[:id])
    @dog.destroy
    redirect_to user_path(@user)
  end

  private
    def dog_params
      params.require(:dog).permit(:name, :birth_date, :gender, :size)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # render signup/login page if user is signed in
  def index
    @user = User.new
  end

  def signup
    @user = User.new
    session[:error] = nil
  end

  def profile
    @user = User.find(session[:user_id])
    redirect_to user_path(@user)
  end

  # render dashboard if user have dog profiles set up
  def dashboard
    @dogs = Dog.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  ERROR_INVALID_LOGIN_DETAILS = "The login details you have entered are invalid."

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])

    # Check if user exists and logs in if details are correct
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      session[:error] = nil

      # render dashboard if user have dog profiles set up
      if user.dogs.length > 0
        redirect_to dashboard_path

      # render user profile if user do not have dog profiles set up
      else
        redirect_to user_path(user)
      end

    # Stay on login page
    else
      session[:error] = ERROR_INVALID_LOGIN_DETAILS
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    session[:error] = nil

    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'pages/signup'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def calc_age(dog)
    age_in_days = Date.today - dog.birth_date;

    # Display age in weeks if less than 1 month old
    if (age_in_days < 28)
      age_in_weeks = age_in_days/7;
      pluralize(age_in_weeks.round, "week")

    # Display age in months if less than 1 year old
    elsif (age_in_days < 365)
      age_in_months = age_in_days/30;
      pluralize(age_in_months.floor, "month")

    # Display age in years if over 1 year old
    else
      age_in_years = age_in_days/365;
      pluralize(age_in_years.floor, "year")
    end
  end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dogs/_form.html.erb
<%= form_with( model: [ @user, @user.dogs.build ], :class => "dog-info-form", local: true ) do |form| %>

  <div class="dog-info-form__entry">
    <div class="entry__header"><%= form.label :name, :class => "dog-info-form__title" %></div>
    <div class="entry__data"><%= form.text_field :name, :class => "dog-info-form__input" %></div>
    <% if @dog.errors.any? %>
      <% if @dog.errors.messages[:name].any? %>
        <p class="dog-info-form__caption error">The dog's name <%= @dog.errors.messages[:name][0] %></p>
      <% end %>
    <% end %>
  </div>

  <div class="dog-info-form__entry">
    <div class="entry__header"><%= form.label :birth_date, :class => "dog-info-form__title" %></div>
    <div class="entry__data"><%= form.date_select :birth_date, {start_year: (Date.today.year - 30), end_year: Date.today.year} %></div>
  </div>

  <div class="dog-info-form__entry">
    <div class="entry__header"><%= form.label :gender, :class => "dog-info-form__title" %></div>
    <div class="entry__data"><%= form.select :gender, ["Male", "Female"] %></div>
  </div>

  <div class="dog-info-form__entry">
    <div class="entry__header"><%= form.label :size, :class => "dog-info-form__title" %></div>
    <div class="entry__data"><%= form.select :size, ["Toy", "Small", "Medium", "Large", "Giant"] %></div>
  </div>

  <div class="form-submit__buttons">
    <%= form.submit "Save dog details", :class => "button button-save" %>
    <%= link_to "Cancel", user_path(@user), :class => "button button-cancel" %>
  </div>

<% end %>

app/views/dogs/_tile.html.erb
<div class="dog-profile">
  <% if params[:controller].eql?("users") %>
    <%= link_to image_tag("cross-default.png", onmouseover: "this.src='#{asset_path('cross-hovered.png')}'", onmouseout:  "this.src='#{asset_path('cross-default.png')}'", class: "dog-profile__photo__remove"),
                [dog.user, dog],
                method: :delete, data: { confirm: "Are you sure you want to delete #{dog.name} from your profile?" }%>
  <% end %>
  <%= image_tag "dog_profile_default.png", class: "dog-profile__photo" %>
  <div class="dog-profile__info">

    <div class="dog-profile__info__row">
      <h3 class="dog-profile__name"><%= dog.name %></h3>
      <% if dog.birth_date? %>
        <p class="dog-profile__age"><%= calc_age(dog) %></p>
      <% end %>
    </div>

    <div class="dog-profile__info__row">
      <% if dog.gender? %>
        <p class="dog-profile__gender"><%= dog.gender %></p>
      <% end %>
      <% if dog.size? %>
        <p class="dog-profile__size"><%= dog.size %></p>
      <% end %>
    </div>

    <div class="center">
      <% if params[:controller].eql?("users") %>
        <%= link_to 'Edit dog profile', edit_user_dog_path(@user, dog), class: "button button-edit" %>
      <% end %>
    </div>

  </div>
</div>

app/views/dogs/edit.html.erb
<div class="page-content-container container">
  <h2 class="page-title">Editing my dog's profile</h2>
  <%= render 'form' %>
</div>

app/views/dogs/new.html.erb
<div class="page-content-container container">
  <h2 class="page-title">Adding a new dog to my profile</h2>
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meet Pup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'pages/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_navbar.html.erb
<nav class="nav-bar">
  <% if session[:user_id] %>
    <h2 class="nav-bar__logo"><%= link_to "Meet Pup", dashboard_path %></h2>
    <div class="nav-bar__item"><%= link_to "Dashboard", dashboard_path %></div>
    <div class="nav-bar__item"><%= link_to "My account", action: :show, controller: 'users' %></div>
    <div class="nav-bar__item"><%= link_to "Log out", logout_path %></div>
  <% end %>

  <% unless session[:user_id] %>
    <h2 class="nav-bar__logo"><%= link_to "Meet Pup", root_path %></h2>
    <div class="nav-bar__item"><%= link_to "Log in", root_path %></div>
    <div class="nav-bar__item"><%= link_to "Sign up", signup_path %></div>
  <% end %>

</nav>

app/views/pages/dashboard.html.erb
<div class="dashboard container">
  <div class="dashboard-section">
    <h2 class="dashboard-section__title page-title">Dogs near me</h2>
    <div class="display-panel">
      <% @dogs.each do | dog | %>
        <% if dog.user_id != session[:user_id] %>
          <%= render 'dogs/tile', dog: dog %>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/pages/index.html.erb
<div class="landing-container container">

  <div class="landing-content wide-screen-width-55 vertical-align">
    <div class="landing-intro">
      <h1 class="landing-intro__logo">Meet Pup</h1>
      <h2 class="landing-intro__heading">Find furry friends for your pups</h2>
      <p class="landing-intro__text">Login to Meet Pup to meet other dogs and dog lovers for exciting play dates!</p>
      <p class="landing-intro__text--alternative">Don't have an account yet? <%= link_to "Sign up", signup_path, class: "link-inline" %> now!</p>
    </div>
  </div>

  <!-- Fix me: Can't seem to add class to render tags -->
  <div class="landing-content wide-screen-width-45">
    <%= render 'users/authenticate' %>
  </div>

</div>

app/views/pages/signup.html.erb
<div class="landing-container container">

  <div class="landing-content wide-screen-width-55 vertical-align">
    <div class="landing-intro">
      <h1 class="landing-intro__logo">Meet Pup</h1>
      <h2 class="landing-intro__heading">Find furry friends for your pups</h2>
      <p class="landing-intro__text">Join Meet Pup today to meet other dogs and dog lovers for exciting play dates!</p>
      <p class="landing-intro__text--alternative">Already have an account? <%= link_to "Log in", root_path, class: "link-inline" %> now!</p>
    </div>
  </div>

  <!-- Fix me: Can't seem to add class to render tags -->
  <div class="landing-content wide-screen-width-45">
    <%= render 'users/signup' %>
  </div>

</div>

app/views/users/_authenticate.html.erb
<%= form_for(:session, url: login_path, :html => {class: "sign-up-form"}, local: true) do |form| %>


  <div class="sign-up-form__entry">
    <%= form.label :username, :class => "sign-up-form__title" %>
    <%= form.text_field :username, :class => "sign-up-form__input" %>
  </div>

  <div class="sign-up-form__entry">
    <%= form.label :password, :class => "sign-up-form__title" %>
    <%= form.password_field :password, :class => "sign-up-form__input" %>
  </div>

  <% if session[:error] %>
    <p class="sign-up-form__caption error"><%= session[:error] %></p>
  <% end %>

  <div class="sign-up-form__entry center">
    <%= form.submit "Log in", class: "button button-add" %>
  </div>

<% end %>

app/views/users/_signup.html.erb
<%= form_with model: @user, :class => "sign-up-form", local: true do |form| %>

  <div class="sign-up-form__entry">
    <%= form.label :username, :class => "sign-up-form__title" %>
    <%= form.text_field :username, :class => "sign-up-form__input" %>
    <% if @user.errors.any? %>
      <% if @user.errors.messages[:username].any? %>
        <p class="sign-up-form__caption error">This username <%= @user.errors.messages[:username][0] %></p>
      <% end %>
    <% end %>
  </div>

  <div class="sign-up-form__entry">
    <%= form.label :email, :class => "sign-up-form__title" %>
    <%= form.text_field :email, :class => "sign-up-form__input" %>
    <% if @user.errors.any? %>
      <% if @user.errors.messages[:email].any? %>
        <p class="sign-up-form__caption error">This email <%= @user.errors.messages[:email][0] %></p>
      <% end %>
    <% end %>
  </div>

  <div class="sign-up-form__entry">
    <%= form.label :password, :class => "sign-up-form__title" %>
    <%= form.password_field :password, :class => "sign-up-form__input" %>
    <% if @user.errors.any? %>
      <% if @user.errors.messages[:password].any? %>
        <p class="sign-up-form__caption error">This password <%= @user.errors.messages[:password][0] %></p>
      <% end %>
    <% end %>
    <p class="sign-up-form__caption">Make sure it's at least 8 characters including a number and a lowercase letter.</p>
  </div>

  <% if params[:controller].eql?("pages") && params[:action].eql?("signup") || (params[:controller].eql?("users") && params[:action].eql?("create")) %>
    <div class="sign-up-form__entry">
      <%= form.submit "Sign up for Meet Pup", :class => "button sign-up-form__button" %>
      <p class="sign-up-form__caption">By clicking "Sign up for Meet Pup", you agree to our <a class="link-inline" href="#">Terms of Service</a> and <a class="link-inline" href="#">Privacy Statement</a>.</p>
    </div>
  <% end %>

  <% if params[:controller].eql?("users") && (params[:action].eql?("edit") || params[:action].eql?("update")) %>
    <div class="form-submit__buttons">
      <%= form.submit "Save account details", :class => "button button-edit" %>
      <%= link_to 'Cancel', user_path(@user), class: "button button-cancel" %>
    </div>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<div class="page-content-container container">
  <h2 class="account-info-title page-title">Edit my account details</h2>
  <%= render 'signup' %>
</div>

app/views/users/index.html.erb
<div class="users-list">
  <h2>A list of users</h2>
  <%= link_to 'Add a new User', new_user_path, class: "button" %>

  <table class="users-list-table">
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="2"></th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<%= render 'signup' %>

app/views/users/show.html.erb
<div class="page-content-container container">
  <h2 class="account-info-title page-title">My account</h2>
  <%= link_to 'Edit account details', edit_user_path(@user), class: "button button-edit" %>
  <div class="account-info-content">
    <div class="account-info-content__entry">
      <div class="entry__header">Username</div>
      <div class="entry__data"><%= @user.username %></div>
    </div>
    <div class="account-info-content__entry">
      <div class="entry__header">Registered email</div>
      <div class="entry__data"><%= @user.email %></div>
    </div>
    <div>
      <div class="account-info-content__entry">
        <div class="entry__header">My dogs</div>
        <%= link_to 'Add dog', new_user_dog_path(@user), class: "button button-add" %>
      </div>
      <div class="display-panel">
        <% @user.dogs.each do | dog | %>
          <%= render 'dogs/tile', dog: dog %>
        <% end %>
      </div>
    </div>
  </div>
  <%= link_to 'Go to dashboard', dashboard_path, class: "button button-edit" %>
</div>